### ISSUE TITLE
Footer warning displays unnecessary padding with using success panels.

### ISSUE THREAD

**Issue by MebinAbraham** [ONSdigital/design-system#1172]
**Describe the bug**
When using the footer warning panel, an additional padding is used when the page also contains a success panel.
Seems to be caused by this which is also used by success pannels:
```css
.panel--no-title {
    padding: 1rem;
    border-left: 8px solid transparent;
}
```

**To Reproduce**

Use a footer warning with success panel.

**Expected behavior**
No extra padding on footer warning panels.

**Screenshots**
![image](https://user-images.githubusercontent.com/35296336/99274377-2df59380-2822-11eb-8d62-53332a166d0e.png)
