### ISSUE TITLE
Default appearance of details/summary arrow is not hidden in Safari on iOS or Mac

### ISSUE THREAD

**Issue by kruncher** [ONSdigital/design-system#2425]
The collapsible component looks wrong with the Safari browser on iOS and Mac:

![Image](https://user-images.githubusercontent.com/554215/187678264-2ed5e152-5c3e-4e1c-a19f-3fcd2e4ea2af.png)

This can be improved with the following CSS:
```css
details > summary {
  list-style: none;
}

details > summary::marker, /* Latest Chrome, Edge, Firefox */ 
details > summary::-webkit-details-marker /* Safari */ {
  display: none;
}
```

The first selector covers other browsers but for Safari the `::-webkit-details-marker` selector is required.

Above solution was found here: https://stackoverflow.com/a/66814239
